USE dbTW
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TRIGGER trg_lastUpdate
ON [dbo].tbToken
AFTER UPDATE , INSERT
AS
BEGIN
    UPDATE [dbo].tbUser
    SET lastUpdateDate = GETDATE()
    WHERE pk_IdUser IN (SELECT DISTINCT pk_IdUser FROM Inserted)

END
GO